// Code generated by mockery v1.0.0
package mocks

import auth "github.com/CloudHub360/ch360.go/auth"
import mock "github.com/stretchr/testify/mock"

// TokenRetriever is an autogenerated mock type for the TokenRetriever type
type TokenRetriever struct {
	mock.Mock
}

// RetrieveToken provides a mock function with given fields: clientId, clientSecret
func (_m *TokenRetriever) RetrieveToken(clientId string, clientSecret string) (*auth.AccessToken, error) {
	ret := _m.Called(clientId, clientSecret)

	var r0 *auth.AccessToken
	if rf, ok := ret.Get(0).(func(string, string) *auth.AccessToken); ok {
		r0 = rf(clientId, clientSecret)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.AccessToken)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(clientId, clientSecret)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
