// Code generated by mockery v1.0.0
package mocks

import io "io"
import mock "github.com/stretchr/testify/mock"

// ClassifierUploader is an autogenerated mock type for the ClassifierUploader type
type ClassifierUploader struct {
	mock.Mock
}

// Upload provides a mock function with given fields: name, contents
func (_m *ClassifierUploader) Upload(name string, contents io.Reader) error {
	ret := _m.Called(name, contents)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, io.Reader) error); ok {
		r0 = rf(name, contents)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
