// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import io "io"
import mock "github.com/stretchr/testify/mock"

// ClassifierTrainer is an autogenerated mock type for the ClassifierTrainer type
type ClassifierTrainer struct {
	mock.Mock
}

// Train provides a mock function with given fields: ctx, name, samplesArchive
func (_m *ClassifierTrainer) Train(ctx context.Context, name string, samplesArchive io.Reader) error {
	ret := _m.Called(ctx, name, samplesArchive)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader) error); ok {
		r0 = rf(ctx, name, samplesArchive)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
