// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"

// ClassificationService is an autogenerated mock type for the ClassificationService type
type ClassificationService struct {
	mock.Mock
}

// ClassifyAll provides a mock function with given fields: ctx, files, classifierName
func (_m *ClassificationService) ClassifyAll(ctx context.Context, files []string, classifierName string) error {
	ret := _m.Called(ctx, files, classifierName)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, string) error); ok {
		r0 = rf(ctx, files, classifierName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
