// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import ch360 "github.com/waives/surf/ch360"

import context "context"
import mock "github.com/stretchr/testify/mock"

// ClassifierDeleterGetter is an autogenerated mock type for the ClassifierDeleterGetter type
type ClassifierDeleterGetter struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, name
func (_m *ClassifierDeleterGetter) Delete(ctx context.Context, name string) error {
	ret := _m.Called(ctx, name)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: ctx
func (_m *ClassifierDeleterGetter) GetAll(ctx context.Context) (ch360.ClassifierList, error) {
	ret := _m.Called(ctx)

	var r0 ch360.ClassifierList
	if rf, ok := ret.Get(0).(func(context.Context) ch360.ClassifierList); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ch360.ClassifierList)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
