// Code generated by mockery v1.0.0
package mocks

import ch360 "github.com/CloudHub360/ch360.go/ch360"

import mock "github.com/stretchr/testify/mock"

// ExtractorGetter is an autogenerated mock type for the ExtractorGetter type
type ExtractorGetter struct {
	mock.Mock
}

// GetAll provides a mock function with given fields:
func (_m *ExtractorGetter) GetAll() (ch360.ExtractorList, error) {
	ret := _m.Called()

	var r0 ch360.ExtractorList
	if rf, ok := ret.Get(0).(func() ch360.ExtractorList); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ch360.ExtractorList)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
