// Code generated by mockery v1.0.0
package mocks

import context "context"
import io "io"
import mock "github.com/stretchr/testify/mock"

// ExtractorCreator is an autogenerated mock type for the ExtractorCreator type
type ExtractorCreator struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, name, config
func (_m *ExtractorCreator) Create(ctx context.Context, name string, config io.Reader) error {
	ret := _m.Called(ctx, name, config)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader) error); ok {
		r0 = rf(ctx, name, config)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
