// Code generated by mockery v1.0.0
package mocks

import context "context"
import io "io"
import mock "github.com/stretchr/testify/mock"
import results "github.com/CloudHub360/ch360.go/ch360/results"

// FileExtractor is an autogenerated mock type for the FileExtractor type
type FileExtractor struct {
	mock.Mock
}

// Extract provides a mock function with given fields: ctx, fileContent, extractorName
func (_m *FileExtractor) Extract(ctx context.Context, fileContent io.Reader, extractorName string) (*results.ExtractionResult, error) {
	ret := _m.Called(ctx, fileContent, extractorName)

	var r0 *results.ExtractionResult
	if rf, ok := ret.Get(0).(func(context.Context, io.Reader, string) *results.ExtractionResult); ok {
		r0 = rf(ctx, fileContent, extractorName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*results.ExtractionResult)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, io.Reader, string) error); ok {
		r1 = rf(ctx, fileContent, extractorName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
