// Code generated by mockery v1.0.0
package mocks

import commands "github.com/CloudHub360/ch360.go/cmd/surf/commands"
import context "context"
import mock "github.com/stretchr/testify/mock"

// FilesProcessor is an autogenerated mock type for the FilesProcessor type
type FilesProcessor struct {
	mock.Mock
}

// RunWithGlob provides a mock function with given fields: ctx, filesPattern, parallelism, processorFuncFactory
func (_m *FilesProcessor) RunWithGlob(ctx context.Context, filesPattern string, parallelism int, processorFuncFactory commands.ProcessorFuncFactory) error {
	ret := _m.Called(ctx, filesPattern, parallelism, processorFuncFactory)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, commands.ProcessorFuncFactory) error); ok {
		r0 = rf(ctx, filesPattern, parallelism, processorFuncFactory)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
