// Code generated by mockery v1.0.0
package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"
import pool "github.com/CloudHub360/ch360.go/pool"

// HandlerFuncFactory is an autogenerated mock type for the HandlerFuncFactory type
type HandlerFuncFactory struct {
	mock.Mock
}

// HandlerFor provides a mock function with given fields: cancel, filename
func (_m *HandlerFuncFactory) HandlerFor(cancel context.CancelFunc, filename string) pool.HandlerFunc {
	ret := _m.Called(cancel, filename)

	var r0 pool.HandlerFunc
	if rf, ok := ret.Get(0).(func(context.CancelFunc, string) pool.HandlerFunc); ok {
		r0 = rf(cancel, filename)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pool.HandlerFunc)
		}
	}

	return r0
}
