// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import ch360 "github.com/CloudHub360/ch360.go/ch360"

import context "context"
import mock "github.com/stretchr/testify/mock"

// ReaderService is an autogenerated mock type for the ReaderService type
type ReaderService struct {
	mock.Mock
}

// ReadAll provides a mock function with given fields: ctx, files, readMode
func (_m *ReaderService) ReadAll(ctx context.Context, files []string, readMode ch360.ReadMode) error {
	ret := _m.Called(ctx, files, readMode)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, ch360.ReadMode) error); ok {
		r0 = rf(ctx, files, readMode)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
