// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"

// RedactWithExtractorService is an autogenerated mock type for the RedactWithExtractorService type
type RedactWithExtractorService struct {
	mock.Mock
}

// RedactAllWithExtractor provides a mock function with given fields: ctx, files, extractorName
func (_m *RedactWithExtractorService) RedactAllWithExtractor(ctx context.Context, files []string, extractorName string) error {
	ret := _m.Called(ctx, files, extractorName)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, string) error); ok {
		r0 = rf(ctx, files, extractorName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
