// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"

// Trainer is an autogenerated mock type for the Trainer type
type Trainer struct {
	mock.Mock
}

// Train provides a mock function with given fields: name, samplesPath
func (_m *Trainer) Train(name string, samplesPath string) error {
	ret := _m.Called(name, samplesPath)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(name, samplesPath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
