// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"

// FileWriter is an autogenerated mock type for the FileWriter type
type FileWriter struct {
	mock.Mock
}

// WriteFile provides a mock function with given fields: filepath, data
func (_m *FileWriter) WriteFile(filepath string, data []byte) error {
	ret := _m.Called(filepath, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []byte) error); ok {
		r0 = rf(filepath, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
