// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import sinks "github.com/waives/surf/output/sinks"

// SinkFactory is an autogenerated mock type for the SinkFactory type
type SinkFactory struct {
	mock.Mock
}

// Sink provides a mock function with given fields: params
func (_m *SinkFactory) Sink(params sinks.SinkParams) (sinks.Sink, error) {
	ret := _m.Called(params)

	var r0 sinks.Sink
	if rf, ok := ret.Get(0).(func(sinks.SinkParams) sinks.Sink); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sinks.Sink)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(sinks.SinkParams) error); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
