// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"

// DocumentCreatorDeleterClassifier is an autogenerated mock type for the DocumentCreatorDeleterClassifier type
type DocumentCreatorDeleterClassifier struct {
	mock.Mock
}

// ClassifyDocument provides a mock function with given fields: documentId, classifierName
func (_m *DocumentCreatorDeleterClassifier) ClassifyDocument(documentId string, classifierName string) (string, error) {
	ret := _m.Called(documentId, classifierName)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(documentId, classifierName)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(documentId, classifierName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateDocument provides a mock function with given fields: fileContents
func (_m *DocumentCreatorDeleterClassifier) CreateDocument(fileContents []byte) (string, error) {
	ret := _m.Called(fileContents)

	var r0 string
	if rf, ok := ret.Get(0).(func([]byte) string); ok {
		r0 = rf(fileContents)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(fileContents)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteDocument provides a mock function with given fields: documentId
func (_m *DocumentCreatorDeleterClassifier) DeleteDocument(documentId string) error {
	ret := _m.Called(documentId)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(documentId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
