// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"

// DocumentCreator is an autogenerated mock type for the DocumentCreator type
type DocumentCreator struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, fileContents
func (_m *DocumentCreator) Create(ctx context.Context, fileContents []byte) (string, error) {
	ret := _m.Called(ctx, fileContents)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, []byte) string); ok {
		r0 = rf(ctx, fileContents)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = rf(ctx, fileContents)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
