// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import ch360 "github.com/waives/surf/ch360"
import context "context"
import io "io"
import mock "github.com/stretchr/testify/mock"

// DocumentCreator is an autogenerated mock type for the DocumentCreator type
type DocumentCreator struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, fileContents
func (_m *DocumentCreator) Create(ctx context.Context, fileContents io.Reader) (ch360.Document, error) {
	ret := _m.Called(ctx, fileContents)

	var r0 ch360.Document
	if rf, ok := ret.Get(0).(func(context.Context, io.Reader) ch360.Document); ok {
		r0 = rf(ctx, fileContents)
	} else {
		r0 = ret.Get(0).(ch360.Document)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, io.Reader) error); ok {
		r1 = rf(ctx, fileContents)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
