// Code generated by pegomock. DO NOT EDIT.
// Source: github.com/CloudHub360/ch360.go/ch360 (interfaces: DocumentDeleter)

package mocks

import (
	context "context"
	pegomock "github.com/petergtz/pegomock"
	"reflect"
	"time"
)

type MockDocumentDeleter struct {
	fail func(message string, callerSkip ...int)
}

func NewMockDocumentDeleter(options ...pegomock.Option) *MockDocumentDeleter {
	mock := &MockDocumentDeleter{}
	for _, option := range options {
		option.Apply(mock)
	}
	return mock
}

func (mock *MockDocumentDeleter) SetFailHandler(fh pegomock.FailHandler) { mock.fail = fh }
func (mock *MockDocumentDeleter) FailHandler() pegomock.FailHandler      { return mock.fail }

func (mock *MockDocumentDeleter) Delete(ctx context.Context, documentId string) error {
	if mock == nil {
		panic("mock must not be nil. Use myMock := NewMockDocumentDeleter().")
	}
	params := []pegomock.Param{ctx, documentId}
	result := pegomock.GetGenericMockFrom(mock).Invoke("Delete", params, []reflect.Type{reflect.TypeOf((*error)(nil)).Elem()})
	var ret0 error
	if len(result) != 0 {
		if result[0] != nil {
			ret0 = result[0].(error)
		}
	}
	return ret0
}

func (mock *MockDocumentDeleter) VerifyWasCalledOnce() *VerifierMockDocumentDeleter {
	return &VerifierMockDocumentDeleter{
		mock:                   mock,
		invocationCountMatcher: pegomock.Times(1),
	}
}

func (mock *MockDocumentDeleter) VerifyWasCalled(invocationCountMatcher pegomock.Matcher) *VerifierMockDocumentDeleter {
	return &VerifierMockDocumentDeleter{
		mock:                   mock,
		invocationCountMatcher: invocationCountMatcher,
	}
}

func (mock *MockDocumentDeleter) VerifyWasCalledInOrder(invocationCountMatcher pegomock.Matcher, inOrderContext *pegomock.InOrderContext) *VerifierMockDocumentDeleter {
	return &VerifierMockDocumentDeleter{
		mock:                   mock,
		invocationCountMatcher: invocationCountMatcher,
		inOrderContext:         inOrderContext,
	}
}

func (mock *MockDocumentDeleter) VerifyWasCalledEventually(invocationCountMatcher pegomock.Matcher, timeout time.Duration) *VerifierMockDocumentDeleter {
	return &VerifierMockDocumentDeleter{
		mock:                   mock,
		invocationCountMatcher: invocationCountMatcher,
		timeout:                timeout,
	}
}

type VerifierMockDocumentDeleter struct {
	mock                   *MockDocumentDeleter
	invocationCountMatcher pegomock.Matcher
	inOrderContext         *pegomock.InOrderContext
	timeout                time.Duration
}

func (verifier *VerifierMockDocumentDeleter) Delete(ctx context.Context, documentId string) *MockDocumentDeleter_Delete_OngoingVerification {
	params := []pegomock.Param{ctx, documentId}
	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "Delete", params, verifier.timeout)
	return &MockDocumentDeleter_Delete_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
}

type MockDocumentDeleter_Delete_OngoingVerification struct {
	mock              *MockDocumentDeleter
	methodInvocations []pegomock.MethodInvocation
}

func (c *MockDocumentDeleter_Delete_OngoingVerification) GetCapturedArguments() (context.Context, string) {
	ctx, documentId := c.GetAllCapturedArguments()
	return ctx[len(ctx)-1], documentId[len(documentId)-1]
}

func (c *MockDocumentDeleter_Delete_OngoingVerification) GetAllCapturedArguments() (_param0 []context.Context, _param1 []string) {
	params := pegomock.GetGenericMockFrom(c.mock).GetInvocationParams(c.methodInvocations)
	if len(params) > 0 {
		_param0 = make([]context.Context, len(params[0]))
		for u, param := range params[0] {
			_param0[u] = param.(context.Context)
		}
		_param1 = make([]string, len(params[1]))
		for u, param := range params[1] {
			_param1[u] = param.(string)
		}
	}
	return
}
