// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import io "io"
import mock "github.com/stretchr/testify/mock"

// FileRedactor is an autogenerated mock type for the FileRedactor type
type FileRedactor struct {
	mock.Mock
}

// Redact provides a mock function with given fields: ctx, fileContent, extractorName
func (_m *FileRedactor) Redact(ctx context.Context, fileContent io.Reader, extractorName string) (io.ReadCloser, error) {
	ret := _m.Called(ctx, fileContent, extractorName)

	var r0 io.ReadCloser
	if rf, ok := ret.Get(0).(func(context.Context, io.Reader, string) io.ReadCloser); ok {
		r0 = rf(ctx, fileContent, extractorName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, io.Reader, string) error); ok {
		r1 = rf(ctx, fileContent, extractorName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
