// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"
import services "github.com/waives/surf/cmd/surf/services"

// FileGlobProcessor is an autogenerated mock type for the FileGlobProcessor type
type FileGlobProcessor struct {
	mock.Mock
}

// RunWithGlob provides a mock function with given fields: ctx, filePatterns, parallelism, processorFuncFactory
func (_m *FileGlobProcessor) RunWithGlob(ctx context.Context, filePatterns []string, parallelism int, processorFuncFactory services.ProcessorFuncFactory) error {
	ret := _m.Called(ctx, filePatterns, parallelism, processorFuncFactory)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, int, services.ProcessorFuncFactory) error); ok {
		r0 = rf(ctx, filePatterns, parallelism, processorFuncFactory)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
