// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import ch360 "github.com/CloudHub360/ch360.go/ch360"
import context "context"
import io "io"
import mock "github.com/stretchr/testify/mock"

// FileReader is an autogenerated mock type for the FileReader type
type FileReader struct {
	mock.Mock
}

// Read provides a mock function with given fields: ctx, fileContent, mode
func (_m *FileReader) Read(ctx context.Context, fileContent io.Reader, mode ch360.ReadMode) (io.ReadCloser, error) {
	ret := _m.Called(ctx, fileContent, mode)

	var r0 io.ReadCloser
	if rf, ok := ret.Get(0).(func(context.Context, io.Reader, ch360.ReadMode) io.ReadCloser); ok {
		r0 = rf(ctx, fileContent, mode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, io.Reader, ch360.ReadMode) error); ok {
		r1 = rf(ctx, fileContent, mode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
