// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"

// ClassifierCommand is an autogenerated mock type for the ClassifierCommand type
type ClassifierCommand struct {
	mock.Mock
}

// Execute provides a mock function with given fields: classifierName
func (_m *ClassifierCommand) Execute(classifierName string) error {
	ret := _m.Called(classifierName)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(classifierName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
