// Code generated by mockery v1.0.0
package mocks

import ch360 "github.com/CloudHub360/ch360.go/ch360"

import mock "github.com/stretchr/testify/mock"

// DeleteGetter is an autogenerated mock type for the DeleteGetter type
type DeleteGetter struct {
	mock.Mock
}

// Delete provides a mock function with given fields: name
func (_m *DeleteGetter) Delete(name string) error {
	ret := _m.Called(name)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields:
func (_m *DeleteGetter) GetAll() ([]ch360.Classifier, error) {
	ret := _m.Called()

	var r0 []ch360.Classifier
	if rf, ok := ret.Get(0).(func() []ch360.Classifier); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ch360.Classifier)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
