// Code generated by mockery v1.0.0
package mocks

import io "io"
import mock "github.com/stretchr/testify/mock"

// WriterProvider is an autogenerated mock type for the WriterProvider type
type WriterProvider struct {
	mock.Mock
}

// Provide provides a mock function with given fields: fullPath
func (_m *WriterProvider) Provide(fullPath string) (io.Writer, error) {
	ret := _m.Called(fullPath)

	var r0 io.Writer
	if rf, ok := ret.Get(0).(func(string) io.Writer); ok {
		r0 = rf(fullPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Writer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(fullPath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
