// Code generated by mockery v1.0.0
package mocks

import io "io"
import mock "github.com/stretchr/testify/mock"

// WriteCloserProvider is an autogenerated mock type for the WriteCloserProvider type
type WriteCloserProvider struct {
	mock.Mock
}

// Provide provides a mock function with given fields: fullPath
func (_m *WriteCloserProvider) Provide(fullPath string) (io.WriteCloser, error) {
	ret := _m.Called(fullPath)

	var r0 io.WriteCloser
	if rf, ok := ret.Get(0).(func(string) io.WriteCloser); ok {
		r0 = rf(fullPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.WriteCloser)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(fullPath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
