// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import http "net/http"
import mock "github.com/stretchr/testify/mock"

// ResponseChecker is an autogenerated mock type for the ResponseChecker type
type ResponseChecker struct {
	mock.Mock
}

// CheckForErrors provides a mock function with given fields: response
func (_m *ResponseChecker) CheckForErrors(response *http.Response) error {
	ret := _m.Called(response)

	var r0 error
	if rf, ok := ret.Get(0).(func(*http.Response) error); ok {
		r0 = rf(response)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
