// Code generated by mockery v1.0.0
package mocks

import http "net/http"
import mock "github.com/stretchr/testify/mock"

// Checker is an autogenerated mock type for the Checker type
type Checker struct {
	mock.Mock
}

// Check provides a mock function with given fields: _a0, successCode
func (_m *Checker) Check(_a0 *http.Response, successCode int) ([]byte, error) {
	ret := _m.Called(_a0, successCode)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(*http.Response, int) []byte); ok {
		r0 = rf(_a0, successCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*http.Response, int) error); ok {
		r1 = rf(_a0, successCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
