// Code generated by mockery v1.0.0
package mocks

import io "io"
import mock "github.com/stretchr/testify/mock"

// Sender is an autogenerated mock type for the Sender type
type Sender struct {
	mock.Mock
}

// Send provides a mock function with given fields: method, path, body
func (_m *Sender) Send(method string, path string, body io.Reader) ([]byte, error) {
	ret := _m.Called(method, path, body)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(string, string, io.Reader) []byte); ok {
		r0 = rf(method, path, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, io.Reader) error); ok {
		r1 = rf(method, path, body)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
