// Code generated by "stringer -type=Verb"; DO NOT EDIT.

package config

import "strconv"

const _Verb_name = "ExtractClassifyLoginListCreateDeleteRead"

var _Verb_index = [...]uint8{0, 7, 15, 20, 24, 30, 36, 40}

func (i Verb) String() string {
	if i < 0 || i >= Verb(len(_Verb_index)-1) {
		return "Verb(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Verb_name[_Verb_index[i]:_Verb_index[i+1]]
}
